package org.example;

import org.junit.jupiter.api.Test;
//This source file was generated by the Gradle 'init' task
import org.openqa.selenium.*;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;


public class Shizoid {
    boolean isPlaying = false;
    public static void main(String[] args) {
        testApp();
    }

    @Test
    public static void testApp() {
        // Set path for chrome-driver
        // System.setProperty("webdriver.chrome.driver", "chromedriver_linux64");
        // Configure ChromeOptions for headless mode
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--headless");
        options.addArguments("--disable-gpu"); // better performance

        // Initialize webdriver with options
        WebDriver driver = new ChromeDriver(options);

        try {    
            boolean isPlaying = false;
            // Open website
            driver.get("http://popupplayer.radio.net/popupplayer/index.html?station=schizoiddubtechno&tenant=www.radio.de&authId=7929a0dd-5120-4bc7-9785-11f9929e35d6");
            Thread.sleep(5);
            while (isPlaying) {
                WebElement play = driver.findElement(By.tagName("g"));
                // System.out.print(play.getText());
                play.click();
            }
        } catch (InterruptedException error) {
            error.printStackTrace();
            driver.quit();
        }
    }

}
    
