package org.example;
import org.junit.jupiter.api.Test;
//This source file was generated by the Gradle 'init' task
import org.openqa.selenium.*;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

//System.setProperty("webdriver.chrome.driver", " ");


public class App {
    public static void main(String[] args) {
 
        //Set path for chrome-driver
        System.setProperty("webdriver.chrome.driver", "chromedriver_linux64/chromedriver");
        //Configure ChromeOptions for headless mode
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--headless");
        options.addArguments("--disable-gpu");  //better performance

        //Initialize webdriver with options
        WebDriver driver = new ChromeDriver(options);

        try {
            //Open website
            //https://www.di.fm/dubtechno
            driver.get("https://mabu-beatz-radio.com/streams/dub-techno/");
            System.out.print("Page title is: " + driver.getTitle());
            Thread.sleep(10);
            WebElement play = driver.findElement(By.id("play"));
            return play.getText();

        } catch (Exception error) {
            error.printStackTrace();
            return "err";
        }
    }
    @Test
    public void testApp() {
        String[] a = {"a","a"};
        //Test code goes here
        main(a);
    }
}
    
